/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    pages: Page;
    events: Event;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock | EventBlock)[];
  meta?: {
    title?: string | null;
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  name?: string | null;
  roles?: ('USER' | 'ADMIN') | null;
  id: string;
  email: string;
  image?: string | null;
  emailVerified?: string | null;
  accounts?:
    | {
        id?: string | null;
        provider: string;
        providerAccountId: string;
        type: string;
      }[]
    | null;
  sessions?:
    | {
        id?: string | null;
        sessionToken: string;
        expires: string;
      }[]
    | null;
  verificationTokens?:
    | {
        id?: string | null;
        token: string;
        expires: string;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventBlock".
 */
export interface EventBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'events' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'events';
        value: number | Event;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  poster: number | Media;
  dateTime: {
    from: string;
    fromTime: string;
    to: string;
    toTime: string;
    timezone:
      | 'Africa/Abidjan'
      | 'Africa/Accra'
      | 'Africa/Addis_Ababa'
      | 'Africa/Algiers'
      | 'Africa/Asmera'
      | 'Africa/Bamako'
      | 'Africa/Bangui'
      | 'Africa/Banjul'
      | 'Africa/Bissau'
      | 'Africa/Blantyre'
      | 'Africa/Brazzaville'
      | 'Africa/Bujumbura'
      | 'Africa/Cairo'
      | 'Africa/Casablanca'
      | 'Africa/Ceuta'
      | 'Africa/Conakry'
      | 'Africa/Dakar'
      | 'Africa/Dar_es_Salaam'
      | 'Africa/Djibouti'
      | 'Africa/Douala'
      | 'Africa/El_Aaiun'
      | 'Africa/Freetown'
      | 'Africa/Gaborone'
      | 'Africa/Harare'
      | 'Africa/Johannesburg'
      | 'Africa/Juba'
      | 'Africa/Kampala'
      | 'Africa/Khartoum'
      | 'Africa/Kigali'
      | 'Africa/Kinshasa'
      | 'Africa/Lagos'
      | 'Africa/Libreville'
      | 'Africa/Lome'
      | 'Africa/Luanda'
      | 'Africa/Lubumbashi'
      | 'Africa/Lusaka'
      | 'Africa/Malabo'
      | 'Africa/Maputo'
      | 'Africa/Maseru'
      | 'Africa/Mbabane'
      | 'Africa/Mogadishu'
      | 'Africa/Monrovia'
      | 'Africa/Nairobi'
      | 'Africa/Ndjamena'
      | 'Africa/Niamey'
      | 'Africa/Nouakchott'
      | 'Africa/Ouagadougou'
      | 'Africa/Porto-Novo'
      | 'Africa/Sao_Tome'
      | 'Africa/Tripoli'
      | 'Africa/Tunis'
      | 'Africa/Windhoek'
      | 'America/Adak'
      | 'America/Anchorage'
      | 'America/Anguilla'
      | 'America/Antigua'
      | 'America/Araguaina'
      | 'America/Argentina/La_Rioja'
      | 'America/Argentina/Rio_Gallegos'
      | 'America/Argentina/Salta'
      | 'America/Argentina/San_Juan'
      | 'America/Argentina/San_Luis'
      | 'America/Argentina/Tucuman'
      | 'America/Argentina/Ushuaia'
      | 'America/Aruba'
      | 'America/Asuncion'
      | 'America/Bahia'
      | 'America/Bahia_Banderas'
      | 'America/Barbados'
      | 'America/Belem'
      | 'America/Belize'
      | 'America/Blanc-Sablon'
      | 'America/Boa_Vista'
      | 'America/Bogota'
      | 'America/Boise'
      | 'America/Buenos_Aires'
      | 'America/Cambridge_Bay'
      | 'America/Campo_Grande'
      | 'America/Cancun'
      | 'America/Caracas'
      | 'America/Catamarca'
      | 'America/Cayenne'
      | 'America/Cayman'
      | 'America/Chicago'
      | 'America/Chihuahua'
      | 'America/Ciudad_Juarez'
      | 'America/Coral_Harbour'
      | 'America/Cordoba'
      | 'America/Costa_Rica'
      | 'America/Creston'
      | 'America/Cuiaba'
      | 'America/Curacao'
      | 'America/Danmarkshavn'
      | 'America/Dawson'
      | 'America/Dawson_Creek'
      | 'America/Denver'
      | 'America/Detroit'
      | 'America/Dominica'
      | 'America/Edmonton'
      | 'America/Eirunepe'
      | 'America/El_Salvador'
      | 'America/Fort_Nelson'
      | 'America/Fortaleza'
      | 'America/Glace_Bay'
      | 'America/Godthab'
      | 'America/Goose_Bay'
      | 'America/Grand_Turk'
      | 'America/Grenada'
      | 'America/Guadeloupe'
      | 'America/Guatemala'
      | 'America/Guayaquil'
      | 'America/Guyana'
      | 'America/Halifax'
      | 'America/Havana'
      | 'America/Hermosillo'
      | 'America/Indiana/Knox'
      | 'America/Indiana/Marengo'
      | 'America/Indiana/Petersburg'
      | 'America/Indiana/Tell_City'
      | 'America/Indiana/Vevay'
      | 'America/Indiana/Vincennes'
      | 'America/Indiana/Winamac'
      | 'America/Indianapolis'
      | 'America/Inuvik'
      | 'America/Iqaluit'
      | 'America/Jamaica'
      | 'America/Jujuy'
      | 'America/Juneau'
      | 'America/Kentucky/Monticello'
      | 'America/Kralendijk'
      | 'America/La_Paz'
      | 'America/Lima'
      | 'America/Los_Angeles'
      | 'America/Louisville'
      | 'America/Lower_Princes'
      | 'America/Maceio'
      | 'America/Managua'
      | 'America/Manaus'
      | 'America/Marigot'
      | 'America/Martinique'
      | 'America/Matamoros'
      | 'America/Mazatlan'
      | 'America/Mendoza'
      | 'America/Menominee'
      | 'America/Merida'
      | 'America/Metlakatla'
      | 'America/Mexico_City'
      | 'America/Miquelon'
      | 'America/Moncton'
      | 'America/Monterrey'
      | 'America/Montevideo'
      | 'America/Montserrat'
      | 'America/Nassau'
      | 'America/New_York'
      | 'America/Nome'
      | 'America/Noronha'
      | 'America/North_Dakota/Beulah'
      | 'America/North_Dakota/Center'
      | 'America/North_Dakota/New_Salem'
      | 'America/Ojinaga'
      | 'America/Panama'
      | 'America/Paramaribo'
      | 'America/Phoenix'
      | 'America/Port-au-Prince'
      | 'America/Port_of_Spain'
      | 'America/Porto_Velho'
      | 'America/Puerto_Rico'
      | 'America/Punta_Arenas'
      | 'America/Rankin_Inlet'
      | 'America/Recife'
      | 'America/Regina'
      | 'America/Resolute'
      | 'America/Rio_Branco'
      | 'America/Santarem'
      | 'America/Santiago'
      | 'America/Santo_Domingo'
      | 'America/Sao_Paulo'
      | 'America/Scoresbysund'
      | 'America/Sitka'
      | 'America/St_Barthelemy'
      | 'America/St_Johns'
      | 'America/St_Kitts'
      | 'America/St_Lucia'
      | 'America/St_Thomas'
      | 'America/St_Vincent'
      | 'America/Swift_Current'
      | 'America/Tegucigalpa'
      | 'America/Thule'
      | 'America/Tijuana'
      | 'America/Toronto'
      | 'America/Tortola'
      | 'America/Vancouver'
      | 'America/Whitehorse'
      | 'America/Winnipeg'
      | 'America/Yakutat'
      | 'Antarctica/Casey'
      | 'Antarctica/Davis'
      | 'Antarctica/DumontDUrville'
      | 'Antarctica/Macquarie'
      | 'Antarctica/Mawson'
      | 'Antarctica/McMurdo'
      | 'Antarctica/Palmer'
      | 'Antarctica/Rothera'
      | 'Antarctica/Syowa'
      | 'Antarctica/Troll'
      | 'Antarctica/Vostok'
      | 'Arctic/Longyearbyen'
      | 'Asia/Aden'
      | 'Asia/Almaty'
      | 'Asia/Amman'
      | 'Asia/Anadyr'
      | 'Asia/Aqtau'
      | 'Asia/Aqtobe'
      | 'Asia/Ashgabat'
      | 'Asia/Atyrau'
      | 'Asia/Baghdad'
      | 'Asia/Bahrain'
      | 'Asia/Baku'
      | 'Asia/Bangkok'
      | 'Asia/Barnaul'
      | 'Asia/Beirut'
      | 'Asia/Bishkek'
      | 'Asia/Brunei'
      | 'Asia/Calcutta'
      | 'Asia/Chita'
      | 'Asia/Colombo'
      | 'Asia/Damascus'
      | 'Asia/Dhaka'
      | 'Asia/Dili'
      | 'Asia/Dubai'
      | 'Asia/Dushanbe'
      | 'Asia/Famagusta'
      | 'Asia/Gaza'
      | 'Asia/Hebron'
      | 'Asia/Hong_Kong'
      | 'Asia/Hovd'
      | 'Asia/Irkutsk'
      | 'Asia/Jakarta'
      | 'Asia/Jayapura'
      | 'Asia/Jerusalem'
      | 'Asia/Kabul'
      | 'Asia/Kamchatka'
      | 'Asia/Karachi'
      | 'Asia/Katmandu'
      | 'Asia/Khandyga'
      | 'Asia/Krasnoyarsk'
      | 'Asia/Kuala_Lumpur'
      | 'Asia/Kuching'
      | 'Asia/Kuwait'
      | 'Asia/Macau'
      | 'Asia/Magadan'
      | 'Asia/Makassar'
      | 'Asia/Manila'
      | 'Asia/Muscat'
      | 'Asia/Nicosia'
      | 'Asia/Novokuznetsk'
      | 'Asia/Novosibirsk'
      | 'Asia/Omsk'
      | 'Asia/Oral'
      | 'Asia/Phnom_Penh'
      | 'Asia/Pontianak'
      | 'Asia/Pyongyang'
      | 'Asia/Qatar'
      | 'Asia/Qostanay'
      | 'Asia/Qyzylorda'
      | 'Asia/Rangoon'
      | 'Asia/Riyadh'
      | 'Asia/Saigon'
      | 'Asia/Sakhalin'
      | 'Asia/Samarkand'
      | 'Asia/Seoul'
      | 'Asia/Shanghai'
      | 'Asia/Singapore'
      | 'Asia/Srednekolymsk'
      | 'Asia/Taipei'
      | 'Asia/Tashkent'
      | 'Asia/Tbilisi'
      | 'Asia/Tehran'
      | 'Asia/Thimphu'
      | 'Asia/Tokyo'
      | 'Asia/Tomsk'
      | 'Asia/Ulaanbaatar'
      | 'Asia/Urumqi'
      | 'Asia/Ust-Nera'
      | 'Asia/Vientiane'
      | 'Asia/Vladivostok'
      | 'Asia/Yakutsk'
      | 'Asia/Yekaterinburg'
      | 'Asia/Yerevan'
      | 'Atlantic/Azores'
      | 'Atlantic/Bermuda'
      | 'Atlantic/Canary'
      | 'Atlantic/Cape_Verde'
      | 'Atlantic/Faeroe'
      | 'Atlantic/Madeira'
      | 'Atlantic/Reykjavik'
      | 'Atlantic/South_Georgia'
      | 'Atlantic/St_Helena'
      | 'Atlantic/Stanley'
      | 'Australia/Adelaide'
      | 'Australia/Brisbane'
      | 'Australia/Broken_Hill'
      | 'Australia/Darwin'
      | 'Australia/Eucla'
      | 'Australia/Hobart'
      | 'Australia/Lindeman'
      | 'Australia/Lord_Howe'
      | 'Australia/Melbourne'
      | 'Australia/Perth'
      | 'Australia/Sydney'
      | 'Europe/Amsterdam'
      | 'Europe/Andorra'
      | 'Europe/Astrakhan'
      | 'Europe/Athens'
      | 'Europe/Belgrade'
      | 'Europe/Berlin'
      | 'Europe/Bratislava'
      | 'Europe/Brussels'
      | 'Europe/Bucharest'
      | 'Europe/Budapest'
      | 'Europe/Busingen'
      | 'Europe/Chisinau'
      | 'Europe/Copenhagen'
      | 'Europe/Dublin'
      | 'Europe/Gibraltar'
      | 'Europe/Guernsey'
      | 'Europe/Helsinki'
      | 'Europe/Isle_of_Man'
      | 'Europe/Istanbul'
      | 'Europe/Jersey'
      | 'Europe/Kaliningrad'
      | 'Europe/Kiev'
      | 'Europe/Kirov'
      | 'Europe/Lisbon'
      | 'Europe/Ljubljana'
      | 'Europe/London'
      | 'Europe/Luxembourg'
      | 'Europe/Madrid'
      | 'Europe/Malta'
      | 'Europe/Mariehamn'
      | 'Europe/Minsk'
      | 'Europe/Monaco'
      | 'Europe/Moscow'
      | 'Europe/Oslo'
      | 'Europe/Paris'
      | 'Europe/Podgorica'
      | 'Europe/Prague'
      | 'Europe/Riga'
      | 'Europe/Rome'
      | 'Europe/Samara'
      | 'Europe/San_Marino'
      | 'Europe/Sarajevo'
      | 'Europe/Saratov'
      | 'Europe/Simferopol'
      | 'Europe/Skopje'
      | 'Europe/Sofia'
      | 'Europe/Stockholm'
      | 'Europe/Tallinn'
      | 'Europe/Tirane'
      | 'Europe/Ulyanovsk'
      | 'Europe/Vaduz'
      | 'Europe/Vatican'
      | 'Europe/Vienna'
      | 'Europe/Vilnius'
      | 'Europe/Volgograd'
      | 'Europe/Warsaw'
      | 'Europe/Zagreb'
      | 'Europe/Zurich'
      | 'Indian/Antananarivo'
      | 'Indian/Chagos'
      | 'Indian/Christmas'
      | 'Indian/Cocos'
      | 'Indian/Comoro'
      | 'Indian/Kerguelen'
      | 'Indian/Mahe'
      | 'Indian/Maldives'
      | 'Indian/Mauritius'
      | 'Indian/Mayotte'
      | 'Indian/Reunion'
      | 'Pacific/Apia'
      | 'Pacific/Auckland'
      | 'Pacific/Bougainville'
      | 'Pacific/Chatham'
      | 'Pacific/Easter'
      | 'Pacific/Efate'
      | 'Pacific/Enderbury'
      | 'Pacific/Fakaofo'
      | 'Pacific/Fiji'
      | 'Pacific/Funafuti'
      | 'Pacific/Galapagos'
      | 'Pacific/Gambier'
      | 'Pacific/Guadalcanal'
      | 'Pacific/Guam'
      | 'Pacific/Honolulu'
      | 'Pacific/Kiritimati'
      | 'Pacific/Kosrae'
      | 'Pacific/Kwajalein'
      | 'Pacific/Majuro'
      | 'Pacific/Marquesas'
      | 'Pacific/Midway'
      | 'Pacific/Nauru'
      | 'Pacific/Niue'
      | 'Pacific/Norfolk'
      | 'Pacific/Noumea'
      | 'Pacific/Pago_Pago'
      | 'Pacific/Palau'
      | 'Pacific/Pitcairn'
      | 'Pacific/Ponape'
      | 'Pacific/Port_Moresby'
      | 'Pacific/Rarotonga'
      | 'Pacific/Saipan'
      | 'Pacific/Tahiti'
      | 'Pacific/Tarawa'
      | 'Pacific/Tongatapu'
      | 'Pacific/Truk'
      | 'Pacific/Wake'
      | 'Pacific/Wallis';
    allDay?: boolean | null;
  };
  location: {
    search?: string | null;
    address: string;
    latitude: number;
    longitude: number;
    locationJson:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  relatedEvents?: (number | Event)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    image?: (number | null) | Media;
    description?: string | null;
  };
  capacity: number;
  registration: 'OPEN' | 'CLOSE';
  authors: (string | User)[];
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'events';
        value: number | Event;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?:
          | T
          | {
              richText?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              columns?:
                | T
                | {
                    size?: T;
                    richText?: T;
                    enableLink?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              id?: T;
              blockName?: T;
            };
        archive?:
          | T
          | {
              introContent?: T;
              populateBy?: T;
              relationTo?: T;
              categories?: T;
              limit?: T;
              selectedDocs?: T;
              id?: T;
              blockName?: T;
            };
        formBlock?:
          | T
          | {
              form?: T;
              enableIntro?: T;
              introContent?: T;
              id?: T;
              blockName?: T;
            };
        eventArchive?:
          | T
          | {
              introContent?: T;
              populateBy?: T;
              relationTo?: T;
              categories?: T;
              limit?: T;
              selectedDocs?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  poster?: T;
  dateTime?:
    | T
    | {
        from?: T;
        fromTime?: T;
        to?: T;
        toTime?: T;
        timezone?: T;
        allDay?: T;
      };
  location?:
    | T
    | {
        search?: T;
        address?: T;
        latitude?: T;
        longitude?: T;
        locationJson?: T;
      };
  relatedEvents?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  capacity?: T;
  registration?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  id?: T;
  email?: T;
  image?: T;
  emailVerified?: T;
  accounts?:
    | T
    | {
        id?: T;
        provider?: T;
        providerAccountId?: T;
        type?: T;
      };
  sessions?:
    | T
    | {
        id?: T;
        sessionToken?: T;
        expires?: T;
      };
  verificationTokens?:
    | T
    | {
        id?: T;
        token?: T;
        expires?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        id?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}